# Generated by Django 6.0.6 on 2026-07-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.CharField(choices=[('NORMAL', 'Normal'), ('READ_ONLY', 'Read Only'), ('FULL_MAINTENANCE', 'Full Maintenance')], default='NORMAL', max_length=30)),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('allow_admin_override', models.BooleanField(default=True)),
            ],
        ),
    ]
