# Generated by Django 6.0.6 on 2026-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
