# Generated by Django 6.0.6 on 2026-07-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0003_issue_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
