# Generated by Django 6.0.6 on 2026-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0004_payment_paid_amount_payment_tenant_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tenant_note',
        ),
        migrations.AddField(
            model_name='payment',
            name='total_rent',
            field=models.FloatField(default=0.0),
        ),
    ]
