# Generated by Django 6.0.6 on 2026-08-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0005_remove_payment_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='demo_mobile_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='demo_mode_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
