# Generated by Django 6.0.6 on 2026-08-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0006_systemsettings_demo_mobile_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_joining_date', models.DateField()),
                ('days_remaining_in_current_hostel', models.IntegerField()),
                ('message_to_owner', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_hostel_requests', to='HAC.stayhosteldetails')),
                ('target_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_hostel_requests', to='HAC.stayhosteldetails')),
                ('target_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_change_requests', to='HAC.owners')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_change_requests', to='HAC.tenent')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'target_hostel', 'status')},
            },
        ),
    ]
