# Generated by Django 6.0.6 on 2026-08-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0006_systemsettings_demo_mobile_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_room', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_bed', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_flat', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacate_requests', to='HAC.owners')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacate_requests', to='HAC.tenent')),
            ],
            options={
                'db_table': 'vacate_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
