# Generated by Django 6.0.6 on 2026-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0007_hostelchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelchangerequest',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelchangerequest',
            name='requested_room_preference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hostelchangerequest',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
