# Generated by Django 6.0.6 on 2026-08-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0007_vacaterequest'),
        ('HAC', '0008_hostelchangerequest_additional_details_and_more'),
    ]

    operations = [
    ]
