# Generated by Django 6.0.6 on 2026-08-25 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0010_hostelchangerequest_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelchangerequest',
            name='current_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_hostel_requests', to='HAC.stayhosteldetails'),
        ),
        migrations.AlterField(
            model_name='hostelchangerequest',
            name='days_remaining_in_current_hostel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hostelchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
